#!/usr/bin/env python3

"""
Python script to finalise the server's env setup

This is called within install.sh once Python and the folder structure have been set up correctly.

Usage: python3 setup_env.py [server_name] [deployed_folder] [auth_provider]
"""

import sys
import secrets
import string
from pathlib import Path
from cryptography.fernet import Fernet

def generate_fernet_key():
    return Fernet.generate_key().decode()

def generate_jwt_secret(length=24):
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def load_env(path: str):
    res = {}
    lines = []
    with open(path, 'r') as f:
        lines = f.readlines()    
    for line in lines:
        stripped_line = line.strip()
        if not stripped_line.strip() or stripped_line[0] == '#':
            continue
        if '=' in stripped_line:
            k, v = stripped_line.split('=', 1)
            res[k] = v
    return res

def main():
    if len(sys.argv) != 5:
        print("Usage: python3 setup_env.py [server_name] [deployed_folder] [auth_provider] [teacher_list]")
        sys.exit(1)

    server_name = sys.argv[1]
    deployed_folder = Path(sys.argv[2]).resolve()
    auth_provider = sys.argv[3]
    teacher_list = sys.argv[4]
    env_path = deployed_folder / "env" / ".env"
    admin_list_path = deployed_folder / "server" / "shared" / "admin_list.py"


    if auth_provider and auth_provider not in {'MSAL', 'GOOGLE'}:
        print("AUTH_PROVIDER must be either MSAL or GOOGLE")
        sys.exit(1)

    values = {}
    if env_path.exists():
        print(f"✅ {env_path} already exists. Loading existing values to preserve as much as possible.")
        values = load_env(env_path)

    print(f"📝 Creating {env_path}... Populating values...")
    env_path.parent.mkdir(parents=True, exist_ok=True)

    values['DEBUG'] = 'False'
    values['SERVER_NAME'] = server_name
    values['AUTH_PROVIDER'] = auth_provider

    if 'GOOGLE_APPLICATION_CREDENTIALS' not in values:
        # values['GOOGLE_APPLICATION_CREDENTIALS'] = 'pythonsponge-google-creds.json'  # not needed on Google machines
        pass
    if 'ENC_KEY' not in values:
        values['ENC_KEY'] = generate_fernet_key()
    if 'JWT_SECRET_KEY' not in values:
        values['JWT_SECRET_KEY'] = generate_jwt_secret()

    if auth_provider == 'GOOGLE':
        if 'GOOGLE_AUTH_CLIENT_ID' not in values:
            while True:
                value = input("Enter your Google authentication CLIENT ID. E.g. xxxx.apps.googleusercontent.com\n")
                if value:
                    values['GOOGLE_AUTH_CLIENT_ID'] = value
                    break
        if 'GOOGLE_AUTH_CLIENT_SECRET' not in values:
            while True:
                value = input("Enter your Google authentication CLIENT SECRET. E.g. XXXXXX-xxxxxxxxxxxxxxxxxxxx\n")
                if value:
                    values['GOOGLE_AUTH_CLIENT_SECRET'] = value
                    break
    elif auth_provider == 'MSAL':
        if 'MSAL_CLIENT_ID' not in values:
            while True:
                value = input("Enter your MSAL app CLIENT ID. E.g. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx\n")
                if value:
                    values['MSAL_CLIENT_ID'] = value
                    break
        if 'MSAL_TENANT_ID' not in values:
            while True:
                value = input("Enter your MSAL app's tenant id. E.g. common (if not within an org)\n")
                if value:
                    values['MSAL_TENANT_ID'] = value
                    break                  

    with env_path.open("w") as f:
        f.write("# auto-generated by install script. You can modify values in place, except for DEBUG, SERVER_NAME, and AUTH_PROVIDER which require rerunnig the install script\n")
        f.write('# install script: \n')
        f.write('# curl -fsSL https://raw.githubusercontent.com/gdenes355/pythonsponge-server/main/tools/install.sh | sudo bash\n')
        for k in values:
            f.write(f"{k}={values[k]}\n")

    with admin_list_path.open("w") as f:
        f.write("# auto-generated by install script.")
        f.write('# install script: \n')
        f.write('# curl -fsSL https://raw.githubusercontent.com/gdenes355/pythonsponge-server/main/tools/install.sh | sudo bash\n')
        f.write(f"ADMINS = {teacher_list.split(';')}")  # list of admin email addresses

    print(f"✅ {env_path} and {admin_list_path} created successfully.")

if __name__ == "__main__":
    main()
